# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resource_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

networks:
  collector_kafka:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
volumes:
  db:
    driver: local