version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    container_name: resource-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resource_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: ghcr.io/thomasvitale/keycloak:17.0.0-amd64 # Use quay.io/keycloak:17.0.0-legacy on Intel processors
    container_name: resource-keycloak
    environment:
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=password
    ports:
      - "8080:8080"
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
volumes:
  db:
    driver: local